import './globals.css'
import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'

  const roboto = Roboto({
    subsets: ['latin'],
    weight:['400','700'],
    variable: '--font-roboto'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br"  className={roboto.variable}>
      <body className='max-w-7xl mx-auto' >{children}</body>
    </html>
  )
}
